# Generated by Django 4.0.3 on 2022-03-08 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('hashkey', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('maker', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='CarVersion',
            fields=[
                ('hashkey', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=255)),
                ('year', models.IntegerField(null=True)),
                ('fuel', models.CharField(max_length=10, null=True)),
                ('gear', models.CharField(max_length=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='car.carmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CarOffer',
            fields=[
                ('hashkey', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('price', models.IntegerField(db_index=True)),
                ('miliage', models.IntegerField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('car_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='car.carversion')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='car.country')),
            ],
        ),
    ]
